"""Shell tab-completion generator and automated installer for demo_cli.

Supports Bash, Zsh, Fish, and PowerShell without external dependencies.
Extracts commands, options, and choices dynamically from ArgumentParser.
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Dict, List, Optional, Tuple


SUPPORTED_SHELLS = ("bash", "zsh", "fish", "powershell")


def extract_cli_metadata(parser: argparse.ArgumentParser) -> Dict[str, Any]:
    """Inspect an ArgumentParser instance and extract subcommands, options, and choices."""
    commands: Dict[str, Dict[str, Any]] = {}
    global_options: List[str] = []

    for action in parser._actions:
        if action.help != argparse.SUPPRESS:
            global_options.extend(action.option_strings)
        if isinstance(action, argparse._SubParsersAction):
            # Maps command name to help text from pseudo-actions
            choice_help = {
                ca.dest: ca.help
                for ca in action._choices_actions
                if getattr(ca, "help", None) != argparse.SUPPRESS
            }
            for name, subparser in action._name_parser_map.items():
                if name.startswith("_"):
                    continue
                opts: List[str] = []
                opt_choices: Dict[str, List[str]] = {}
                sub_commands: Dict[str, List[str]] = {}

                for subaction in subparser._actions:
                    if getattr(subaction, "help", None) == argparse.SUPPRESS:
                        continue
                    opts.extend(subaction.option_strings)
                    if subaction.choices:
                        for opt in subaction.option_strings:
                            opt_choices[opt] = [str(c) for c in subaction.choices]
                    if isinstance(subaction, argparse._SubParsersAction):
                        for sub_name in subaction._name_parser_map.keys():
                            if not sub_name.startswith("_"):
                                sub_commands.setdefault(name, []).append(sub_name)

                commands[name] = {
                    "help": choice_help.get(name, "") or "",
                    "options": sorted(set(opts)),
                    "choices": opt_choices,
                    "subcommands": sub_commands.get(name, []),
                }

    return {
        "commands": commands,
        "global_options": sorted(set(global_options)),
    }


def generate_bash_completion(spec: Dict[str, Any]) -> str:
    """Generate a self-contained Bash completion script."""
    commands = spec["commands"]
    all_cmds = " ".join(sorted(commands.keys()))
    global_opts = " ".join(spec["global_options"])

    cases: List[str] = []
    for cmd, data in sorted(commands.items()):
        opts = " ".join(data["options"])
        choice_cases: List[str] = []
        for opt, choices in data["choices"].items():
            choice_str = " ".join(choices)
            choice_cases.append(f"""                {opt})
                    COMPREPLY=($(compgen -W "{choice_str}" -- "$cur"))
                    return 0
                    ;;""")
        if data.get("subcommands"):
            subcmds_str = " ".join(data["subcommands"])
            choice_cases.append(f"""                *)
                    if [[ $cword -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "{subcmds_str}" -- "$cur"))
                        return 0
                    fi
                    COMPREPLY=($(compgen -W "{opts} {global_opts}" -- "$cur"))
                    return 0
                    ;;""")
        else:
            choice_cases.append(f"""                *)
                    COMPREPLY=($(compgen -W "{opts} {global_opts}" -- "$cur"))
                    return 0
                    ;;""")

        joined_choices = "\n".join(choice_cases)
        cases.append(f"""        {cmd})
            case "$prev" in
{joined_choices}
            esac
            ;;""")

    all_cases = "\n".join(cases)

    return f"""# bash completion for demo_cli
# Generated by `demo_cli completion bash`

_demo_cli_completion() {{
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n = || return
    else
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        words=("${{COMP_WORDS[@]}}")
        cword=$COMP_CWORD
    fi

    local commands="{all_cmds}"

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$commands {global_opts}" -- "$cur"))
        return 0
    fi

    local cmd="${{words[1]}}"
    case "$cmd" in
{all_cases}
        *)
            COMPREPLY=($(compgen -W "{global_opts}" -- "$cur"))
            return 0
            ;;
    esac
}}

complete -F _demo_cli_completion demo_cli
"""


def generate_zsh_completion(spec: Dict[str, Any]) -> str:
    """Generate a self-contained Zsh completion script."""
    commands = spec["commands"]

    cmd_desc_lines: List[str] = []
    for cmd, data in sorted(commands.items()):
        help_text = (data["help"] or "no description").replace("'", "").replace("[", "").replace("]", "")
        cmd_desc_lines.append(f"        '{cmd}:{help_text}'")

    cases: List[str] = []
    for cmd, data in sorted(commands.items()):
        opt_lines: List[str] = []
        for opt in data["options"]:
            if opt in data["choices"]:
                c_str = f"({' '.join(data['choices'][opt])})"
                opt_lines.append(f"                    '{opt}[choice]:choice:{c_str}' \\")
            else:
                opt_lines.append(f"                    '{opt}' \\")
        if data.get("subcommands"):
            sub_str = f"({' '.join(data['subcommands'])})"
            opt_lines.append(f"                    '1:action:{sub_str}' \\")
        if opt_lines:
            joined_opts = "\n".join(opt_lines).rstrip(" \\")
            cases.append(f"""                {cmd})
                    _arguments -s \\
{joined_opts}
                    ;;""")

    all_cmd_descs = "\n".join(cmd_desc_lines)
    all_cases = "\n".join(cases)

    return f"""#compdef demo_cli
# zsh completion for demo_cli
# Generated by `demo_cli completion zsh`

_demo_cli() {{
    local -a commands
    commands=(
{all_cmd_descs}
    )

    _arguments -C \\
        '(-h --help)'{{-h,--help}}'[show help]' \\
        '--version[show version]' \\
        '--no-color[disable color]' \\
        '--root[ledger root directory]:directory:_files -/' \\
        '1:command:->command' \\
        '*::args:->args'

    case $state in
        command)
            _describe -t commands 'demo_cli commands' commands
            ;;
        args)
            case $words[1] in
{all_cases}
            esac
            ;;
    esac
}}

_demo_cli "$@"
"""


def generate_fish_completion(spec: Dict[str, Any]) -> str:
    """Generate a self-contained Fish completion script."""
    commands = spec["commands"]
    lines: List[str] = [
        "# fish completion for demo_cli",
        "# Generated by `demo_cli completion fish`",
        "complete -c demo_cli -f",
        "",
        "# Global options",
        'complete -c demo_cli -n "__fish_use_subcommand" -s h -l help -d "show help"',
        'complete -c demo_cli -n "__fish_use_subcommand" -l version -d "show version"',
        'complete -c demo_cli -n "__fish_use_subcommand" -l no-color -d "disable color"',
        'complete -c demo_cli -n "__fish_use_subcommand" -l root -d "ledger root directory"',
        "",
        "# Subcommands",
    ]

    for cmd, data in sorted(commands.items()):
        help_text = (data["help"] or "").replace('"', '\\"')
        lines.append(
            f'complete -c demo_cli -n "__fish_use_subcommand" -a "{cmd}" -d "{help_text}"'
        )

    lines.append("")
    lines.append("# Subcommand options")
    for cmd, data in sorted(commands.items()):
        for opt in data["options"]:
            clean_opt = opt.lstrip("-")
            prefix = "-s" if len(clean_opt) == 1 else "-l"
            if opt in data["choices"]:
                choices_str = " ".join(data["choices"][opt])
                lines.append(
                    f'complete -c demo_cli -n "__fish_seen_subcommand_from {cmd}" {prefix} {clean_opt} -a "{choices_str}"'
                )
            else:
                lines.append(
                    f'complete -c demo_cli -n "__fish_seen_subcommand_from {cmd}" {prefix} {clean_opt}'
                )
        if data.get("subcommands"):
            sub_str = " ".join(data["subcommands"])
            lines.append(
                f'complete -c demo_cli -n "__fish_seen_subcommand_from {cmd}" -a "{sub_str}"'
            )

    return "\n".join(lines) + "\n"


def generate_powershell_completion(spec: Dict[str, Any]) -> str:
    """Generate a self-contained PowerShell completion script."""
    commands = spec["commands"]
    cmds_quoted = ", ".join(f"'{c}'" for c in sorted(commands.keys()))

    return f"""# PowerShell completion for demo_cli
# Generated by `demo_cli completion powershell`

Register-ArgumentCompleter -Native -CommandName demo_cli -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $subcommands = @({cmds_quoted})
    $elements = $commandAst.Elements

    if ($elements.Count -le 2) {{
        $subcommands | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }}
        return
    }}

    $subcommand = $elements[1].Value
    switch ($subcommand) {{
        'completion' {{
            @('bash', 'zsh', 'fish', 'powershell') | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }}
        }}
        'check' {{
            if ($elements[-2].Value -eq '--mode') {{
                @('shadow', 'enforce') | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
        }}
    }}
}}
"""


def generate_completion(shell: str, parser: Optional[argparse.ArgumentParser] = None) -> str:
    """Generate the completion script for the requested shell."""
    if parser is None:
        from .cli import build_parser
        parser = build_parser()

    spec = extract_cli_metadata(parser)
    shell_lower = shell.lower()

    if shell_lower == "bash":
        return generate_bash_completion(spec)
    elif shell_lower == "zsh":
        return generate_zsh_completion(spec)
    elif shell_lower == "fish":
        return generate_fish_completion(spec)
    elif shell_lower in ("powershell", "pwsh"):
        return generate_powershell_completion(spec)
    else:
        raise ValueError(f"Unsupported shell: {shell}. Supported: {', '.join(SUPPORTED_SHELLS)}")


def detect_shell() -> Optional[str]:
    """Detect active shell from environment. Returns None if in CI or unidentifiable."""
    if os.environ.get("CI") or os.environ.get("GITHUB_ACTIONS"):
        return None
    if os.name == "nt":
        return "powershell"

    shell_path = os.environ.get("SHELL", "").strip()
    if not shell_path:
        return "bash"

    base = os.path.basename(shell_path).lower()
    for s in ("zsh", "fish", "bash"):
        if s in base:
            return s

    return "bash"


def install_completion(
    shell: Optional[str] = None,
    home_dir: Optional[str] = None,
    parser: Optional[argparse.ArgumentParser] = None,
) -> Tuple[bool, str]:
    """Install completion script into the appropriate user directory.

    Fail-safe: returns (status, human_readable_message) and never raises.
    """
    try:
        chosen_shell = (shell or detect_shell() or "bash").lower()
        if chosen_shell not in SUPPORTED_SHELLS:
            return False, f"Unsupported shell '{chosen_shell}'. Supported: {', '.join(SUPPORTED_SHELLS)}"

        home = home_dir or os.path.expanduser("~")
        script_content = generate_completion(chosen_shell, parser=parser)

        if chosen_shell == "bash":
            dest_dir = os.path.join(home, ".local", "share", "bash-completion", "completions")
            os.makedirs(dest_dir, exist_ok=True)
            dest_file = os.path.join(dest_dir, "demo_cli")
            with open(dest_file, "w", encoding="utf-8") as f:
                f.write(script_content)
            return True, f"Installed Bash completion to {dest_file}\nTab completion will be active in new shell sessions."

        elif chosen_shell == "fish":
            dest_dir = os.path.join(home, ".config", "fish", "completions")
            os.makedirs(dest_dir, exist_ok=True)
            dest_file = os.path.join(dest_dir, "demo_cli.fish")
            with open(dest_file, "w", encoding="utf-8") as f:
                f.write(script_content)
            return True, f"Installed Fish completion to {dest_file}\nTab completion will be active in new shell sessions."

        elif chosen_shell == "zsh":
            dest_dir = os.path.join(home, ".zfunc")
            os.makedirs(dest_dir, exist_ok=True)
            dest_file = os.path.join(dest_dir, "_demo_cli")
            with open(dest_file, "w", encoding="utf-8") as f:
                f.write(script_content)

            # Ensure fpath is active in .zshrc
            zshrc = os.path.join(home, ".zshrc")
            snippet = "\n# demo_cli zsh completion\nfpath=(~/.zfunc $fpath)\nautoload -Uz compinit && compinit -u 2>/dev/null || true\n"
            if os.path.exists(zshrc):
                content = open(zshrc, encoding="utf-8", errors="ignore").read()
                if ".zfunc" not in content:
                    with open(zshrc, "a", encoding="utf-8") as f:
                        f.write(snippet)
            return True, f"Installed Zsh completion to {dest_file}\nTab completion will be active in new shell sessions."

        elif chosen_shell in ("powershell", "pwsh"):
            if os.name == "nt":
                dest_dir = os.path.join(home, "Documents", "PowerShell")
            else:
                dest_dir = os.path.join(home, ".config", "powershell")
            os.makedirs(dest_dir, exist_ok=True)
            dest_file = os.path.join(dest_dir, "Microsoft.PowerShell_profile.ps1")

            marker = "demo_cli completion"
            already = os.path.exists(dest_file) and marker in open(dest_file, encoding="utf-8", errors="ignore").read()
            if not already:
                with open(dest_file, "a", encoding="utf-8") as f:
                    f.write(f"\n# {marker}\n{script_content}\n")
            return True, f"Configured PowerShell completion in {dest_file}\nTab completion will be active in new sessions."

        return False, f"Unhandled shell: {chosen_shell}"

    except Exception as exc:
        return False, f"Could not install shell completion: {exc}"

